feat: count_of_games_by_season tests and method complete
DarbySmith/futbol pull request #10
Opened 2022-09-15 01:41 UTC by knestler

2022-09-15 13:39 UTC, DarbySmith requested changes
There is a missing end on line 59 in the stat_tracker_spec.rb that caused the test to fail. If you add it back, it will pass. The spec harness tests passed with this change as well.

2022-09-15 13:42 UTC, DarbySmith commented
I added an end on line 59 on the stat_tracker_spec - test passed!

2022-09-15 13:42 UTC, DarbySmith approved these changes

2022-09-16 00:15 UTC, Sergio-Azcona approved these changes

2022-09-16 00:20 UTC, Sergio-Azcona commented
there seemed to be some line blank-space issue but that conflict is now resolved.

2022-09-16 00:20 UTC, merged