Teamstatsrefactor1 (split team into its own file and spec file, and added id module)
DarbySmith/futbol pull request #20
Opened 2022-09-20 13:17 UTC by WilliamLampke

good job gang

2022-09-20 20:06 UTC, knestler approved these changes

2022-09-20 22:41 UTC, DarbySmith requested changes
We need to keep the method names in stat_tracker and then call them from the class they're in:

2022-09-21 15:20 UTC, Sergio-Azcona commented on lib/game.rb
>  class Game
in our final refactor: you can inherit as Darby and i do and just initialize the additional data set needed

2022-09-21 15:21 UTC, DarbySmith approved these changes

2022-09-21 15:24 UTC, Sergio-Azcona approved these changes

2022-09-21 15:25 UTC, Sergio-Azcona commented
Nice Job, Will!!

2022-09-21 15:25 UTC, merged